if(!window.Element){Element=function(){};var __createElement=document.createElement;document.createElement=function(e){var e=__createElement(e),i;for(i in Element.prototype)e[i]=Element.prototype[i];return e};var __getElementById=document.getElementById;document.getElementById=function(e){var e=__getElementById(e),i;for(i in Element.prototype)e[i]=Element.prototype[i];return e}}
var itemPool=[{type:"mask",image:"mask-1.png",value:1},{type:"mask",image:"mask-2.png",value:2},{type:"mask",image:"mask-3.png",value:3},{type:"mask",image:"mask-4.png",value:4},{type:"mask",image:"mask-5.png",value:5},{type:"mask",image:"mask-6.png",value:6},{type:"mask",image:"mask-7.png",value:7},{type:"body",image:"body-1.png",value:1},{type:"body",image:"body-2.png",value:2},{type:"gloves",image:"gloves-1.png",value:1},{type:"gloves",image:"gloves-2.png",value:2},{type:"gloves",image:"gloves-3.png",
value:3},{type:"pants",image:"pants-1.png",value:1},{type:"boots",image:"boots-1.png",value:1},{type:"boots",image:"boots-2.png",value:2},{type:"boots",image:"boots-3.png",value:3},{type:"boots",image:"boots-4.png",value:4},{type:"boots",image:"boots-5.png",value:5},{type:"suit",image:"suit-1.png",value:1},{type:"suit",image:"suit-2.png",value:2},{type:"suit",image:"suit-3.png",value:3},{type:"suit",image:"suit-4.png",value:4}],scenarios=[{mask:[{value:6,safety:10,effect:10},{value:7,safety:5,effect:5}],
body:[],suit:[{value:1,safety:5,effect:5}],pants:[],gloves:[{value:3,safety:5,effect:5},{value:2,safety:5,effect:5}],boots:[{value:5,safety:3,effect:5},{value:4,safety:4,effect:4}],scoring:{mask:30,body:0,suit:10,pants:0,gloves:20,boots:8,time:10},text:"You are on your way to a contaminated area. All the info we've been given is that there is an unknown agent in the air. Good luck!",background:"bga.png",title:"Unknown Agent"},{mask:[{value:3,safety:1,effect:1},{value:2,safety:2,effect:2}],body:[{value:3,
safety:1,effect:1},{value:2,safety:2,effect:2}],suit:[{value:1,safety:2,effect:1},{value:2,safety:2,effect:2}],pants:[{value:3,safety:1,effect:1},{value:2,safety:2,effect:2}],gloves:[{value:3,safety:1,effect:1},{value:2,safety:2,effect:2}],boots:[{value:3,safety:1,effect:1},{value:2,safety:2,effect:2}],text:"Guess who got the short end of the stick? You guessed right! Heres a broom, you get to clean up the mess from the exercise event.",background:"bgb.png",title:"Exercise Cleanup"},{mask:[{value:1,
safety:1,effect:1},{value:3,safety:2,effect:2}],body:[{value:1,safety:1,effect:1},{value:3,safety:2,effect:2}],suit:[{value:1,safety:2,effect:1},{value:2,safety:2,effect:2}],pants:[{value:1,safety:1,effect:1},{value:3,safety:2,effect:2}],gloves:[{value:1,safety:1,effect:1},{value:3,safety:2,effect:2}],boots:[{value:1,safety:1,effect:1},{value:3,safety:2,effect:2}],text:"Look man people are dead and the sky is falling! Not really, but theres this warehouse thats contaminated with radioactive debris and materials, and I sure as heck don't want to go in. We need some special documents.. and yes those documents are last years tax returns.. totally forgot them. Its nice being the boss.",
background:"bgc.png",title:"Radioactive Material"},{mask:[{value:1,safety:2,effect:1},{value:2,safety:2,effect:2}],body:[{value:1,safety:2,effect:1},{value:2,safety:2,effect:2}],suit:[{value:1,safety:2,effect:1},{value:2,safety:2,effect:2}],pants:[{value:1,safety:2,effect:1},{value:2,safety:2,effect:2}],gloves:[{value:1,safety:2,effect:1},{value:2,safety:2,effect:2}],boots:[{value:1,safety:2,effect:1},{value:2,safety:2,effect:2}],text:"So theres this 3 level warehouse and it has a lot of stairs and since Im a pretty hefty guy who enjoys his fair share of donuts, I think its a good idea to send you. There was something mentioned about cyanide gas. Good luck!",
background:"bgd.png",title:"Gas Attack"}];
(function(){function e(){this.gameContainer=document.getElementById("game-container");this.setupMenu()}function i(b,a){var c="N/A";0!==a&&(b=100*(b/a),30>=b?c="F":30<b&&50>=b?c="D":50<b&&70>=b?c="C":70<b&&90>=b?c="B":90<b&&(c="A"));return c}function f(b,a){void 0!==b.innerText?b.innerText=a:b.textContent=a}function k(b,a){return b.className.match(RegExp("(\\s|^)"+a+"(\\s|$)"))}function h(b,a){k(b,a)||(b.className+=" "+a)}function o(b,a){k(b,a)&&(b.className=b.className.replace(RegExp("(\\s|^)"+a+
"(\\s|$)")," "))}function m(b){var b=b.getBoundingClientRect(),a=document.body,c=document.documentElement,d=window.pageYOffset||c.scrollTop||a.scrollTop,j=window.pageXOffset||c.scrollLeft||a.scrollLeft,g=c.clientTop||a.clientTop||0,r=c.clientLeft||a.clientLeft||0,a=b.top+d-g,c=b.left+j-r,j=b.right+j-r,b=b.bottom+d-g;return{x:Math.round(c),y:Math.round(a),width:Math.round(j-c),height:Math.round(b-a)}}this.Dressup=e;e.prototype.setup=function(b){var a=document.createDocumentFragment();this.scenarioNumber=
b;this.currentScenario=scenarios[b];this.gameArea=document.createElement("div");this.playArea=document.createElement("div");this.sortArea=document.createElement("div");this.timer=document.createElement("div");this.timerBar=document.createElement("div");this.gameArea.setAttribute("id","game");this.playArea.setAttribute("id","play-area");this.sortArea.setAttribute("id","sort-area");this.timer.setAttribute("id","timer-container");this.timerBar.setAttribute("id","timer-bar");this.gameContainer.appendChild(this.gameArea);
this.gameArea.appendChild(this.playArea);this.gameArea.appendChild(this.sortArea);this.playArea.appendChild(this.timer);this.timer.appendChild(this.timerBar);this.sortNav=document.createElement("div");this.sortArea.appendChild(this.sortNav);this.sortNav.setAttribute("id","sort-nav");this.tabSuit=document.createElement("button");f(this.tabSuit,"Suits");this.tabHead=document.createElement("button");f(this.tabHead,"Head");this.tabShirts=document.createElement("button");f(this.tabShirts,"Shirts");this.tabPants=
document.createElement("button");f(this.tabPants,"Pants");this.tabGloves=document.createElement("button");f(this.tabGloves,"Gloves");this.tabBoots=document.createElement("button");f(this.tabBoots,"Boots");this.sortNav.appendChild(this.tabSuit);this.sortNav.appendChild(this.tabHead);this.sortNav.appendChild(this.tabShirts);this.sortNav.appendChild(this.tabPants);this.sortNav.appendChild(this.tabGloves);this.sortNav.appendChild(this.tabBoots);this.playArea.style.background="url(images/bgs/"+this.currentScenario.background+
")";document.body.appendChild(this.gameContainer);var c=this;this.gameArea.addEventListener("mousedown",function(a){c.clicked(a,c)},!1);this.gameArea.addEventListener("mouseup",function(a){c.placement(a,c)},!1);this.gameArea.addEventListener("mousemove",function(a){c.dragging(a,c)},!1);this.tabSuit.addEventListener("click",function(a){c.toggle(a,"suit")},!1);this.tabHead.addEventListener("click",function(a){c.toggle(a,"mask")},!1);this.tabPants.addEventListener("click",function(a){c.toggle(a,"pants")},
!1);this.tabShirts.addEventListener("click",function(a){c.toggle(a,"body")},!1);this.tabGloves.addEventListener("click",function(a){c.toggle(a,"gloves")},!1);this.tabBoots.addEventListener("click",function(a){c.toggle(a,"boots")},!1);this.itemPool=itemPool.slice(0);this.dragEvent=this.dragObj=null;this.targetParts=[];this.sortItems=[];for(var a=document.createDocumentFragment(),b=0,d=this.itemPool.length;b<d;b++){var j=document.createElement("div"),g=Math.floor(Math.random()*this.itemPool.length);
this.sortItems.push({element:j,type:this.itemPool[g].type,value:this.itemPool[g].value});h(j,"sort-item");h(j,this.itemPool[g].type);j.style.background="url(images/items/"+this.itemPool[g].image+")";this.itemPool.splice(g,1);a.appendChild(j)}this.sortArea.appendChild(a);for(b=0;b<this.sortItems.length;b++)j=this.sortItems[b].element,a=m(j),j.style.left=Math.random()*(480-a.width)+"px",j.style.top=50+Math.random()*(550-a.height)+"px";a=document.createDocumentFragment();this.modelHead=document.createElement("div");
this.modelBody=document.createElement("div");this.modelSuit=document.createElement("div");this.modelHands=document.createElement("div");this.modelLegs=document.createElement("div");this.modelFeet=document.createElement("div");this.modelTemplate=document.createElement("div");this.modelHead.setAttribute("id","model-head");this.modelBody.setAttribute("id","model-body");this.modelSuit.setAttribute("id","model-suit");this.modelHands.setAttribute("id","model-hands");this.modelLegs.setAttribute("id","model-legs");
this.modelFeet.setAttribute("id","model-feet");this.checkButton=document.createElement("button");this.checkButton.setAttribute("id","check-button");f(this.checkButton,"Check");this.checkButton.addEventListener("click",function(a){c.score(a,c)},!1);this.modelTemplate.setAttribute("id","man-template");a.appendChild(this.modelHead);a.appendChild(this.modelBody);a.appendChild(this.modelSuit);a.appendChild(this.modelHands);a.appendChild(this.modelLegs);a.appendChild(this.modelFeet);a.appendChild(this.modelTemplate);
a.appendChild(this.checkButton);this.playArea.appendChild(a);a=m(this.modelHead);this.targetParts.push({type:"mask",width:a.width,height:a.height,x:a.x,y:a.y,element:this.modelHead,curItems:[]});a=m(this.modelBody);this.targetParts.push({type:"body",width:a.width,height:a.height,x:a.x,y:a.y,element:this.modelBody,curItems:[]});a=m(this.modelSuit);this.targetParts.push({type:"suit",width:a.width,height:a.height,x:a.x,y:a.y,element:this.modelSuit,curItems:[]});a=m(this.modelHands);this.targetParts.push({type:"gloves",
width:a.width,height:a.height,x:a.x,y:a.y,element:this.modelHands,curItems:[]});a=m(this.modelLegs);this.targetParts.push({type:"pants",width:a.width,height:a.height,x:a.x,y:a.y,element:this.modelLegs,curItems:[]});a=m(this.modelFeet);this.targetParts.push({type:"boots",width:a.width,height:a.height,x:a.x,y:a.y,element:this.modelFeet,curItems:[]});this.roundTime=2E4;this.gameTimeOut=null;c.toggle({},"suit");this.modal({content:this.currentScenario.text,dialog:{text:"Shall we begin?",callback:function(a,
b){b.countDownOverlay=document.createElement("div");h(b.countDownOverlay,"overlay");b.countDownElem=document.createElement("div");b.countDownElem.setAttribute("id","countdown");b.counter=4;f(b.countDownElem,b.counter);b.gameArea.appendChild(b.countDownOverlay);b.gameArea.appendChild(b.countDownElem);b.countDown()}},noExit:!0})};e.prototype.preGameScreen=function(){var b=this,a=document.createDocumentFragment(),c=document.createElement("div"),d=document.createElement("div"),j=document.createElement("div"),
g=document.createElement("div");c.setAttribute("id","splash");d.setAttribute("id","easy");j.setAttribute("id","hard");g.setAttribute("id","back");h(d,"ui-button");h(j,"ui-button");h(g,"ui-button");a.appendChild(c);a.appendChild(d);a.appendChild(j);a.appendChild(g);this.gameContainer.appendChild(a);d.addEventListener("click",function(){b.changeLevel();b.scenerioSelection()},!1);j.addEventListener("click",function(){b.changeLevel();b.scenerioSelection()},!1);g.addEventListener("click",function(){b.changeLevel();
b.setupMenu()},!1)};e.prototype.scenerioSelection=function(){var b=this,a=document.createDocumentFragment(),c=document.createElement("div");c.setAttribute("id","splash");a.appendChild(c);for(var c=function(a){return function(){b.changeLevel();b.setup(a)}},d=0;d<scenarios.length;d++)scenarioElem=document.createElement("div"),h(scenarioElem,"ui-button scenario"),scenarioElem.setAttribute("id","scenario-"+d),scenarioElem.style.top=150+60*d+"px",f(scenarioElem,scenarios[d].title),a.appendChild(scenarioElem),
scenarioElem.addEventListener("click",c(d));c=document.createElement("div");h(c,"ui-button");c.setAttribute("id","back");c.style.top=150+60*scenarios.length+"px";a.appendChild(c);c.addEventListener("click",function(){b.changeLevel();b.preGameScreen()},!1);this.gameContainer.appendChild(a)};e.prototype.setupMenu=function(){var b=this,a=document.createDocumentFragment(),c=document.createElement("div"),d=document.createElement("div"),j=document.createElement("div"),g=document.createElement("div");c.setAttribute("id",
"splash");d.setAttribute("id","newgame");j.setAttribute("id","howtoplay");g.setAttribute("id","info");h(d,"ui-button");h(j,"ui-button");h(g,"ui-button");a.appendChild(c);a.appendChild(d);a.appendChild(j);a.appendChild(g);this.gameContainer.appendChild(a);d.addEventListener("click",function(){b.changeLevel();b.preGameScreen()},!1);j.addEventListener("click",function(){b.modal()},!1)};e.prototype.information=function(){};e.prototype.changeLevel=function(){this.gameContainer.innerHTML=""};e.prototype.countDown=
function(){var b=this;this.counter--;0>this.counter?(b.gameArea.removeChild(b.countDownOverlay),b.gameArea.removeChild(b.countDownElem),b.startTime=(new Date).getTime(),b.endTime=b.startTime+b.roundTime,b.timeLeft=(new Date).getTime()-b.startTime,b.update()):(0===this.counter?f(b.countDownElem,"GO!"):f(b.countDownElem,this.counter),setTimeout(function(){b.countDown()},800))};e.prototype.update=function(){this.timeLeft=this.endTime-(new Date).getTime();0<this.timeLeft&&(this.timer.style.width=100*
(this.timeLeft/this.roundTime)+"%");var b=this;0<this.timeLeft/this.roundTime?this.gameTimeOut=setTimeout(function(){b.update()},20):this.modal({content:"You have failed",dialog:{text:"Retry",callback:function(a,b){b.gameContainer.removeChild(b.gameArea);b.setup(b.scenarioNumber)}}})};e.prototype.clicked=function(b,a){null==b&&(b=window.event);var c=null!=b.target?b.target:b.srcElement;if((1==b.button&&null!=window.event||0==b.button)&&k(c,"sort-item")){a.dragObj={};a.dragObj.partsOver={mask:!1,body:!1,
pants:!1,gloves:!1,boots:!1};for(var d=0;d<this.sortItems.length;d++)c===this.sortItems[d].element&&(a.dragObj.type=this.sortItems[d].type,a.dragObj.value=this.sortItems[d].value);a.dragObj.offset=m(c);d=a.dragObj.offset;d.x=b.clientX-d.x;d.y=b.clientY-d.y;c.style.zIndex=1E3;a.dragObj.element=c;c.style.left=b.clientX-d.x+"px";c.style.top=b.clientY-d.y+"px";h(c,"dragging");this.gameArea.appendChild(c);document.body.focus();document.onselectstart=function(){return false};c.ondragstart=function(){return false};
a.checkOver(b,a);return!1}};e.prototype.dragging=function(b,a){null==b&&(b=window.event);a.dragObj&&a.checkOver(b,a)};e.prototype.checkOver=function(b,a){var c=a.dragObj,d=c.offset;c.element.style.left=b.clientX-d.x+"px";c.element.style.top=b.clientY-d.y+"px";for(var j=m(c.element),d=j.x,g=j.y,e=j.width,j=j.height,f=0;f<a.targetParts.length;f++){var h=a.targetParts[f].x,i=a.targetParts[f].y,k=a.targetParts[f].width,p=a.targetParts[f].height;c.partsOver[a.targetParts[f].type]=(d>h||d+e>h)&&d<h+k&&
(g>i||g+j>i)&&g<i+p?!0:!1}};e.prototype.placement=function(b,a){var c=a.dragObj;if(null!==c){o(c.element,"dragging");o(c.element,"placed");document.onselectstart=null;c.element.ondragstart=null;if(c.partsOver[c.type])for(var d=0;d<a.targetParts.length;d++){if(a.targetParts[d].type==c.type){c.element.style.left=a.targetParts[d].x+"px";c.element.style.top=a.targetParts[d].y+"px";a.targetParts[d].value=a.dragObj.value;a.targetParts[d].curItems.push({el:c.element,value:a.dragObj.value});h(c.element,"placed");
break}}else for(d=0;d<a.targetParts.length;d++){c=a.targetParts[d].curItems;for(b=0;b<c.length;b++)if(c[b].el===a.dragObj.element){c.splice(b,1);break}}a.dragObj=null}};e.prototype.score=function(b,a){a.safetyScore=0;a.effectScore=0;a.timeScore=0;a.overallScore=0;for(var c=a.currentScenario.scoring,d=0,j="F",g={mask:{safety:0,effect:0,rank:"F"},body:{safety:0,effect:0,rank:"F"},suit:{safety:0,effect:0,rank:"F"},pants:{safety:0,effect:0,rank:"F"},gloves:{safety:0,effect:0,rank:"F"},boots:{safety:0,
effect:0,rank:"F"}},j=0;j<a.targetParts.length;j++){for(var e=this.currentScenario[a.targetParts[j].type],k=e.length,l=a.targetParts[j],n=0;n<k;n++)for(var m=l.curItems.length,p=l.curItems,q=0;q<m;q++)e[n].value==p[q].value&&(a.safetyScore+=e[n].safety,a.effectScore+=e[n].effect,g[l.type].safety+=e[n].safety,g[l.type].effect+=e[n].effect);d+=c[l.type];g[l.type].rank=i(g[l.type].safety+g[l.type].effect,c[l.type])}clearTimeout(a.gameTimeOut);a.timeScore=Math.ceil(a.timeLeft/1E3);a.overallScore=a.safetyScore+
a.effectScore+a.timeScore;for(j=i(a.safetyScore+a.effectScore,d+c.time);a.sortArea.hasChildNodes();)a.sortArea.removeChild(a.sortArea.lastChild);a.toggle("");a.sortArea.innerHTML="<h2>Scores</h2><table><thead><tr><th>Item</th><th>Safety</th><th>Effectiveness</th><th>Rank</th></tr></thead><tr><td>Head</td><td>"+g.mask.safety+"</td><td>"+g.mask.effect+"</td><td>"+g.mask.rank+"<td></tr><tr><td>Body</td><td>"+g.body.safety+"</td><td>"+g.body.safety+"</td><td>"+g.body.rank+"<td></tr><tr><td>Suit</td><td>"+
g.suit.safety+"</td><td>"+g.suit.safety+"</td><td>"+g.suit.rank+"<td></tr><tr><td>Gloves</td><td>"+g.gloves.safety+"</td><td>"+g.gloves.safety+"</td><td>"+g.gloves.rank+"<td></tr><tr><td>Pants</td><td>"+g.pants.safety+"</td><td>"+g.pants.safety+"</td><td>"+g.pants.rank+"<td></tr><tr><td>Boots</td><td>"+g.boots.safety+"</td><td>"+g.boots.safety+"</td><td>"+g.boots.rank+"<td></tr><tr><td>Totals</td><td>"+a.safetyScore+"</td><td>"+a.effectScore+"</td></tr><tr><td>Overall</td><td> Time Bonus "+a.timeScore+
"</td><td> Overall Score "+a.overallScore+"</td><td>Overall Rank "+j+"</td></tr></table><h3>Overall Rank <span class='rank-"+j+"'>"+j+"</h3>";c=document.createElement("button");h(c,"score");f(c,"Retry");c.addEventListener("click",function(){a.gameContainer.removeChild(a.gameArea);a.setup(a.scenarioNumber)});a.sortArea.appendChild(c);c=document.createElement("button");h(c,"score");f(c,"Exit");c.addEventListener("click",function(){a.gameContainer.removeChild(a.gameArea);a.setupMenu()});a.sortArea.appendChild(c)};
e.prototype.modal=function(b){var a=this,c=document.createDocumentFragment(),d=this.gameContainer,e=m(this.gameContainer),g=document.createElement("div"),i=document.createElement("div"),k=document.createElement("button");h(g,"overlay");h(i,"modal");c.appendChild(g);c.appendChild(i);var l=document.createElement("div");h(l,"content");l.innerHTML=b.content;i.appendChild(l);if(b){if(b.width&&(i.style.width=b.width+"px",i.style.left=(e.width-b.width)/2+"px"),b.height&&(i.style.height=b.height+"px",i.style.top=
(e.height-b.height)/2+"px"),b.dialog){var l=document.createElement("button"),n="ok";b.dialog.text&&(n=b.dialog.text);f(l,n);var o=function(){return true};b.dialog.callback&&(o=b.dialog.callback);l.addEventListener("click",function(b){o(b,a);d.removeChild(i);d.removeChild(g)},!1);i.appendChild(l)}}else b={content:"forgot to pass params?"};b.noExit||(f(k,"Exit"),i.appendChild(k),k.addEventListener("click",function(){d.removeChild(i);d.removeChild(g);a.gameContainer.removeChild(a.gameArea);a.setupMenu()},
!1));d.appendChild(c);b=m(i);i.style.left=parseInt((e.width-b.width)/2,10)+"px"};e.prototype.toggle=function(b,a){var c={mask:!1,body:!1,pants:!1,gloves:!1,boots:!1,suit:!1},d="mask body pants gloves boots suit".split(" ");c[a]=!0;for(var e=0;e<d.length;e++){var g=c[d[e]],f;var i=d[e];if(document.getElementsByClassName)f=document.getElementsByClassName(i);else{f=document.getElementsByTagName("*");for(var h=0,m=[],i=RegExp("(^|\\s)"+i+"(\\s|$)"),h=0;h<f.length;h++)null!==f[h].className.match(i)&&m.push(f[h]);
f=m}h="none";g&&(h="block");for(g=f.length;g--;)k(f[g],"placed")||(f[g].style.display=h)}}})();
if(!Element.prototype.addEventListener){var oListeners={},runListeners=function(e){e||(e=window.event);for(var i=0,f=0,k=oListeners[e.type];f<k.aEls.length;f++)if(k.aEls[f]===this){for(i;i<k.aEvts[f].length;i++)k.aEvts[f][i].call(this,e);break}};Element.prototype.addEventListener=function(e,i){if(oListeners.hasOwnProperty(e)){for(var f=oListeners[e],k=-1,h=0;h<f.aEls.length;h++)if(f.aEls[h]===this){k=h;break}if(-1===k)f.aEls.push(this),f.aEvts.push([i]),this["on"+e]=runListeners;else{f=f.aEvts[k];
this["on"+e]!==runListeners&&(f.splice(0),this["on"+e]=runListeners);for(k=0;k<f.length;k++)if(f[k]===i)return;f.push(i)}}else oListeners[e]={aEls:[this],aEvts:[[i]]},this["on"+e]=runListeners};Element.prototype.removeEventListener=function(e,i){if(oListeners.hasOwnProperty(e)){for(var f=oListeners[e],k=-1,h=0;h<f.aEls.length;h++)if(f.aEls[h]===this){k=h;break}if(-1!==k){h=0;for(f=f.aEvts[k];h<f.length;h++)f[h]===i&&f.splice(h,1)}}}};